Repository dvmonroe/release-notes, pull requests merged in 2018-11, with the labels that each got.

#3 Update README.md
  README.md
Labels: code review

#4 update ruby version
  .ruby-version
Labels: code review

#5 add rubocop, fix cops
  .rubocop.yml
  lib/generators/release/notes/install/install_generator.rb
  lib/release/notes.rb
  lib/release/notes/configuration.rb
  lib/release/notes/date_format.rb
  lib/release/notes/git.rb
  lib/release/notes/link.rb
  lib/release/notes/log.rb
  lib/release/notes/pretty_print.rb
  lib/release/notes/railtie.rb
  lib/release/notes/version.rb
  lib/release/notes/write.rb
  release-notes.gemspec
  spec/release/integration_spec.rb
  spec/release/notes/configuration_spec.rb
  spec/release/notes/git_spec.rb
  spec/release/notes/link_spec.rb
  spec/release/notes/pretty_print_spec.rb
  spec/release/notes/write_spec.rb
  spec/release/notes_spec.rb
  spec/spec_helper.rb
  spec/support/shared_contexts/rake.rb
  spec/tasks/update_release_notes_spec.rb
Labels: code review

#10 Remove extra header underline
  lib/release/notes/write.rb
Labels: code review

#8 update travis config to utilize caching
  .travis.yml
Labels: code review

#13 wrap release notes task with puts
  lib/tasks/update_release_notes.rake
Labels: code review

#7 Increase test coverage
  Gemfile
  bin/console
  lib/release/notes/configuration.rb
  lib/release/notes/link.rb
  lib/release/notes/log.rb
  lib/release/notes/pretty_print.rb
  lib/release/notes/write.rb
  release-notes.gemspec
  spec/release/notes/configuration_spec.rb
  spec/release/notes/date_format_spec.rb
  spec/release/notes/git_spec.rb
  spec/release/notes/link_spec.rb
  spec/release/notes/pretty_print_spec.rb
  spec/release/notes/system_spec.rb
  spec/release/notes/with_configuration_spec.rb
  spec/release/notes/write_spec.rb
  spec/spec_helper.rb
  spec/tasks/update_release_notes_spec.rb
Labels: code review, enhancement

#17 remove extra new line ;B
  lib/release/notes/write.rb
Labels: bug, code review

#12 refactor link
  lib/release/notes/link.rb
  spec/release/notes/link_spec.rb
Labels: code review, enhancement

#21 Reduce cyclomatic complexity of write ;B
  lib/release/notes/log.rb
  lib/release/notes/write.rb
  spec/release/notes/write_spec.rb
  spec/spec_helper.rb
Labels: code review, enhancement

#24 add github templates ;F
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: code review, feature

#26 fix spelling error in pr template ;B
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, code review

#20 issue-15 ;B
  lib/release/notes/link.rb
  spec/release/notes/link_spec.rb
Labels: bug, code review

#16 add force_rewrite option ;F
  README.md
  lib/release/notes/configuration.rb
  lib/release/notes/log.rb
  lib/release/notes/write.rb
Labels: code review, feature

#23 Add log_all ;F
  README.md
  lib/generators/release/notes/install/templates/release_notes.rb
  lib/release/notes/configuration.rb
  lib/release/notes/git.rb
  lib/release/notes/log.rb
  lib/release/notes/system.rb
  spec/release/notes/git_spec.rb
Labels: code review, feature

#25 fix cops and depreciation warnings ;E
  .rubocop.yml
  .travis.yml
  lib/release/notes/configuration.rb
  lib/release/notes/link.rb
  lib/release/notes/log.rb
  lib/release/notes/write.rb
  lib/tasks/update_release_notes.rake
  release-notes.gemspec
  spec/release/notes/configuration_spec.rb
  spec/spec_helper.rb
Labels: code review, enhancement

#29 remove env from rake task ;B
  lib/tasks/update_release_notes.rake
  spec/tasks/update_release_notes_spec.rb
Labels: bug, code review

#30 Update README.md
  README.md
Labels: code review

#38 run rspec tests with travis ;B
  .travis.yml
Labels: bug, code review

#37 use double quotes in config ;F
  lib/generators/release/notes/install/templates/release_notes.rb
Labels: code review, feature

#36 fix issue#34
  lib/release/notes/git.rb
  lib/release/notes/system.rb
Labels: bug, code review

#35 Output the line if not prettifying
  lib/release/notes/write.rb
Labels: code review, wip

#39 fix cognitive complexity of split_words ;F
  lib/release/notes/link.rb
Labels: code review, refactor
