Repository dvmonroe/release-notes, pull requests merged in 2018-12, with the labels that each got.

#43 Fix for issue 40 ;F
  .rubocop.yml
  lib/release/notes/configuration.rb
  lib/release/notes/link.rb
  lib/release/notes/log.rb
Labels: code review, feature

#41 remove invert log ;B
  .travis.yml
  lib/release/notes/git.rb
  lib/release/notes/system.rb
  spec/release/notes/git_spec.rb
  spec/release/notes/system_spec.rb
Labels: bug, code review

#51 add logo ;F
  README.md
Labels: code review, feature

#49 explain how grep works ;F
  README.md
Labels: code review, feature

#47 Make the date/tag a configurable option for grouped output ;F
  .rubocop.yml
  README.md
  lib/generators/release/notes/install/templates/README
  lib/generators/release/notes/install/templates/release_notes.rb
  lib/release/notes/configuration.rb
  lib/release/notes/log.rb
  lib/release/notes/write.rb
  spec/release/notes/configuration_spec.rb
Labels: code review, feature

#59 Don't dupe commits
  .rubocop.yml
  README.md
  lib/generators/release/notes/install/templates/release_notes.rb
  lib/release/notes/configuration.rb
  lib/release/notes/git.rb
  lib/release/notes/log.rb
  spec/integration/default_spec.rb
  spec/release/notes/git_spec.rb
  spec/release/notes/system_spec.rb
Labels: code review

#57 Fixes force_rewrite bug
  lib/release/notes/log.rb
Labels: bug, code review
