Repository dvmonroe/release-notes, pull requests merged in 2019-01, with the labels that each got.

#63 fix yardoc link
  README.md
Labels: code review, feature

#65 update code of conduct to 1.4.0 of contributor covenant
  CODE_OF_CONDUCT.md
Labels: code review, feature

#61 Fix error when tracking commits
  README.md
  lib/generators/release/notes/install/templates/release_notes.rb
  lib/release/notes/configuration.rb
  lib/release/notes/git.rb
  lib/release/notes/log.rb
  spec/integration/default_spec.rb
Labels: bug, wip

#62 Add ability to test against ruby 2.6.0
  .rubocop.yml
  .travis.yml
  release-notes.gemspec
Labels: code review, feature

#68 fix cognitive method complexity in log
  lib/release/notes/log.rb
Labels: code review, feature

#71 Issue #34 Add Documentation
  lib/release/notes/commits.rb
  lib/release/notes/date_formatter.rb
  lib/release/notes/git.rb
  lib/release/notes/link.rb
  lib/release/notes/log.rb
  lib/release/notes/prettify.rb
  lib/release/notes/system.rb
  lib/release/notes/tag.rb
  lib/release/notes/write.rb
Labels: code review

#74 fix issue#73
  lib/release/notes/configurable.rb
  lib/release/notes/configuration.rb
  lib/release/notes/git.rb
  spec/release/notes/configuration_spec.rb
Labels: bug, code review

#77 remove backslash for linked labels
  lib/release/notes/link.rb
  spec/release/notes/link_spec.rb
Labels: code review, feature
